### ISSUE TITLE
✖ use of undeclared identifier 'response'% [gcc]

### ISSUE THREAD

**Issue by wilfrantz** [BaseMax/cUrlC#1]
response is undeclared here.
`	printf("Response:\n%s\n", response);`

**Comment by BaseMax** [comment]
Hello @wilfrantz,

Thank you so much for your message and attention.

https://github.com/BaseMax/cUrlC/commit/ec0889d5abdf6b3775b3051b0c9e69099d00e99c
Solved.

Best,
Max
